### ISSUE TITLE
[Design] 상영관 별 시간 컴포넌트 (시간 선택 뷰)

### ISSUE THREAD

**Issue by gonn-i** [SOPT-all/35-COLLABORATION-WEB-LOTTE_CINEMA#22]
# 🛠 Issue
---

시간 선택 페이지에 있는, 하단 부분인 상영관 별 시간 컴포넌트를 구현하고 페이지의 하단부를 구축한다.

# 📝 To-do
---

 - [x] 시간 블록 컴포넌트 구현
 - [x] 상영관 정보 (전체 / 일반관 / 스페셜관 / Atmos) 상수 처리 후, / UI에서 불러오기 
 - [x] 시간 정보 => 전체 / 조조 / 13시 이후 /  19시 이후 / 심야 필터링 부분 UI 구현
 - [x] 하드코딩으로 상영관에 따른 시간 구현
 - [x]  아코디언 형태로 변환
