### ISSUE TITLE
[Design] 인기차트 컴포넌트 (메인화면 뷰)

### ISSUE THREAD

**Issue by look-back-luca** [SOPT-all/35-COLLABORATION-WEB-LOTTE_CINEMA#23]
# 🛠 Issue
---
메인 페이지의 중앙 부분 인기차트 컴포넌트를 구현한다.

# 📝 To-do
---

- [x] 인기차트 필터별(전체 / 상영중 / 상영예정) 영화 세 편 + 광고 한 편 컴포넌트 만들기 
- [x] 예매하기 버튼 기능 만들기
- [x] 우선은 하드코딩으로 작업하고 나중에 api 붙이기
- [ ] 전체보기 버튼 만들기 (기능 없음)
- [ ] 더 수정하기
