### ISSUE TITLE
[Design] 영화관 지역 선택 컴포넌트 구현 (영화관 선택 뷰)

### ISSUE THREAD

**Issue by constantly-dev** [SOPT-all/35-COLLABORATION-WEB-LOTTE_CINEMA#25]
# 🛠 Issue
영화관 선택 페이지의 지역(큰 범위 & 세분화 지역)을 선택하는 컴포넌트를 구현한다.

# 📝 To-do
- [x] 2개 범위 지역 컴포넌트 UI 구현
- [x] 필터 Pin 컴포넌트 UI 구현
- [x] 영화관 Tab 버튼 (일반관, 스페셜관) 컴포넌트 UI 구현
- [x] 영화관 선택 버튼 컴포넌트 UI 구현
- [x] 목업 데이터로 지역 데이터 관리 & UI 표현
- [x] 지역 세부 데이터 영역 스크롤 추가
