### ISSUE TITLE
[Feat] 영화관 지역 선택 기능 구현 (영화관 선택 뷰)

### ISSUE THREAD

**Issue by constantly-dev** [SOPT-all/35-COLLABORATION-WEB-LOTTE_CINEMA#26]
# 🛠 Issue
영화관 지역을 선택할 때 체크 UI가 표시되고, 아래 핀으로 선택된 지역을 표시하는 기능 구현

# 📝 To-do
### 지역 선택 
- [x] 지역 선택(클릭) 시 UI 표시 (왼쪽 : 흰색 배경 / 오른쪽 : 텍스트 색상 변경 및 체크 표시)
- [x] 지역 선택(클릭) 시 하단 Pin 표시
- [x] Pin 취소 기능 구현

### 버튼
- [x] 영화관 선택 버튼 활성화 상태 분리
