### ISSUE TITLE
[Design] 영화/영화관 정보 컴포넌트 구현 (정보 확인 및 인원 선택 뷰)

### ISSUE THREAD

**Issue by constantly-dev** [SOPT-all/35-COLLABORATION-WEB-LOTTE_CINEMA#36]
# 🛠 Issue
정보 확인 및 인원 선택 페이지의 상단 부분에 해당하는 영화와 영화관 정보를 확인하는 컴포넌트를 구현

# 📝 To-do
- [x] 임시 영화 포스터 사용
- [x] 영화/영화관 정보 임시 데이터 사용
- [x] 전 페이지에서 데이터 어떻게 받아올 지 설계
