### ISSUE TITLE
[Feat] 영화/영화관 정보 확인 및 인원 선택 페이지 구현 (정보 확인 및 인원 선택 뷰)

### ISSUE THREAD

**Issue by constantly-dev** [SOPT-all/35-COLLABORATION-WEB-LOTTE_CINEMA#38]
# 🛠 Issue
정보 확인 및 인원 선택 페이지의 중앙 부분과 하단 인원 선택 UI를 구현하고, 이외 상태 관리 로직 및 상태에 따른 UI 분기를 구현

# 📝 To-do
- [x] 좌석 정보 확인 컴포넌트 UI 구현
- [x] 좌석 선택 컴포넌트 UI 및 상태 관리 구현
- [x] 다음 버튼 컴포넌트 UI 구현
- [x] 이전 페이지 정보 불러오는 방법 설계
