### ISSUE TITLE
[Feat] 좌석 정보 조회 API 연결

### ISSUE THREAD

**Issue by constantly-dev** [SOPT-all/35-COLLABORATION-WEB-LOTTE_CINEMA#77]
# 🛠 Issue
영화 정보 확인 페이지 내 좌석 정보 조회 API 연결

# 📝 To-do
- [ ] 좌석 정보 조회 API 연결 (GET)
- [ ] 다음 버튼 클릭 시 좌석 선택 페이지로 라우팅
- [ ] 좌석 선택 페이지 라우팅 시 인원 정보 state로 보내주기 (Object)
