### ISSUE TITLE
[Init] svgr, config 파일 초기 세팅

### ISSUE THREAD

**Issue by constantly-dev** [SOPT-all/35-COLLABORATION-WEB-LOTTE_CINEMA#8]
# 🛠 Issue
- svgr 초기 세팅 (vite-plugin-svgr)
- tsconfig 파일 설정 (+app, node)

# 📝 To-do

- [ ] vite-plugin-svgr install
- [ ] svgr 관련 설정 (tsconfig 파일 & d.ts 파일)
- [ ] config 파일 설정 (vite.config.ts / tsconfig.json)
